services:
  frontend_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: msm-react-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app #Sync local code (hot-reload)

      #Isolate node_modules (Important due to OS difference).
      #To add dependencies, use docker-compose exec frontend npm install, or rebuild for every local installation.
      - /app/node_modules 
  
  orchestrator_dev:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile.dev
    container_name: msm-orchestrator-dev
    ports:
      - "8080:8080"
    volumes:
      #DEV hot reload
      - ./orchestrator:/usr/src/app
      
      #Give container access to the host's Docker daemon.
      - /var/run/docker.sock:/var/run/docker.sock
      #Ensure that the internally created service source code becomes accesible to the docker daemon.
      - ./microservices:/usr/src/app/microservices
    environment:
      #Used to know the host dir where the daemon should look at from inside the container
      - HOST_SOURCE_PATH=${PWD}

  runner-flask:
    build:
      context: ./runners
      dockerfile: runner-flask
    image: msm-runner-flask
    #Only built to produce the image, never actually run as a service
    #Actual containers are spawned by the orchestrator at runtime.
    profiles:
      - build-only
