services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: MSManager-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app #B: Sync local code (hot-reload)

      #B: Isolate node_modules (Important due to OS difference).
      #B: To add dependencies, use docker-compose exec frontend npm install, or rebuild for every local installation.
      - /app/node_modules 
  
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    container_name: MSManager-orchestrator
    ports:
      - "8080:8080"
    volumes:
      #B: give container access to the host's Docker daemon.
      - /var/run/docker.sock:/var/run/docker.sock

  runner-flask:
    build:
      context: ./runners
      dockerfile: runner-flask
    image: msmanager-runner-flask
    #B: This service is only built to produce the image — it should not run on its own.
    #B: Actual containers are spawned by the orchestrator at runtime.
    profiles:
      - build-only
