FROM golang:1.25.6

WORKDIR /usr/src/app

RUN go install github.com/air-verse/air@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./
RUN go mod download

CMD swag init -g cmd/api/main.go && air
