definitions:
  internal.PullImageRequest:
    properties:
      imageId:
        type: string
    type: object
info:
  contact: {}
paths:
  /images/pull:
    post:
      consumes:
      - application/json
      description: Pulls a Docker image from a registry. If the image already exists
        locally, skips the pull.
      parameters:
      - description: Image to pull
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal.PullImageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Pull a Docker image
      tags:
      - images
swagger: "2.0"
